<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWpf>true</UseWpf> 
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SemanticKernel" Version="1.77.0" />
    <PackageReference Include="Microsoft.SemanticKernel.Connectors.Ollama" Version="1.77.0-alpha" />
    <PackageReference Include="SharpToken" Version="2.0.6" />
  </ItemGroup>

  <!-- Please adjust according to the actual relative path in your environment. -->
  <ItemGroup>
    <ProjectReference Include="..\WmiQueryTool\WmiQueryTool.csproj" />
  </ItemGroup>

</Project>